server:
  address: 127.0.0.1
  port: 30005
---
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: ${server.address}
        port: ${server.port}
        health-check-path: /actuator/health
        health-check-interval: 15s
---
spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
      - id: default
        uri: http://${server.address}:${server.port}/404
        order: 10000
        predicates:
        - Path=/**
      - id: peach-service-meituan
        uri: http://${server.address}:${server.port}/404
        order: 9000
        predicates:
        - Path=/meituan/**