server:
  address: 127.0.0.1
  port: 30106
  servlet:
    context-path: /peach-service-eleme
---
spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        hostname: ${server.address}
        port: ${server.port}
        service-name: ${spring.application.name}
        health-check-path: ${server.servlet.context-path}/actuator/health
        health-check-interval: 15s
---
spring:
  jackson:
    default-property-inclusion: NON_NULL
    property-naming-strategy: SNAKE_CASE
    locale: SIMPLIFIED_CHINESE
    time-zone: "Asia/Shanghai"
    date-format: "yyyy-MM-dd HH:mm:ss"