server:
  address: 127.0.0.1
  port: 30106
  servlet:
    context-path: /${spring.application.name}
---
spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        hostname: ${server.address}
        port: ${server.port}
        service-name: ${spring.application.name}
        health-check-path: ${server.servlet.context-path}/actuator/health
        health-check-interval: 15s
---
spring:
  jackson:
    default-property-inclusion: NON_NULL
    property-naming-strategy: SNAKE_CASE
    locale: SIMPLIFIED_CHINESE
    time-zone: "Asia/Shanghai"
    date-format: "yyyy-MM-dd HH:mm:ss"
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/peach?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: peach
    password: peach
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: PeachHikariCP
      minimum-idle: 5
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
---
mybatis:
    type-aliases-package: com.kopever.peach.service.eleme.domain.data
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
---
feign:
  hystrix:
    enabled: true
---
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
---
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000
---
logging:
  level:
    com.kopever.peach.service.eleme.client.UserClient: DEBUG