server:
  address: 127.0.0.1
  port: 30005
---
spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        hostname: ${server.address}
        port: ${server.port}
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 15s
---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: default
        uri: http://${server.address}:${server.port}/404
        order: 10000
        predicates:
        - Path=/**
      - id: peach-service-eleme
        uri: lb://peach-service-eleme
        order: 9000
        predicates:
        - Path=/eleme/**
        filters:
        - RewritePath=/eleme/(?<segment>.*), /peach-service-eleme/$\{segment}
      - id: peach-service-meituan
        uri: lb://peach-service-meituan
        order: 8000
        predicates:
        - Path=/meituan/{segment}
        filters:
        - SetPath=/peach-service-meituan/{segment}