server:
  address: 127.0.0.1
  port: 30105
  servlet:
    context-path: /peach-service-meituan
---
spring:
  security:
    user:
      name: password
      password: name
---
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: ${server.servlet.context-path}/health
        health-check-interval: 15s